# Generated by Django 5.2.7 on 2026-02-04 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['latitude', 'longitude'], name='shops_shop_latitud_e4840a_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['owner'], name='shops_shop_owner_i_de9788_idx'),
        ),
    ]
